import { useRef } from 'react'
import { FileDown, Printer } from 'lucide-react'
import * as api from '../../services'
import { useAsync } from '../../hooks/useAsync'
import { Badge, Button, Card, ErrorNote, PageHeader, Spinner } from '../../components/ui'
import { DataTable } from '../../components/cards'
import { RiskPie } from '../../components/charts'
import { fmtDate, fmtDateTime } from '../../utils/format'
import { FOOTER_NOTE } from '../../types'
import type { ReportT } from '../../types'

export default function Reports() {
  const list = useAsync(() => api.fetchReportsList(), true)
  const overview = useAsync(() => api.fetchOverviewReport(), true)
  const printRef = useRef<HTMLDivElement>(null)

  const doPrint = () => window.print()

  if (overview.status === 'loading') return <Spinner label="Preparing reports…" />
  if (overview.error) return <ErrorNote message={overview.error} onRetry={overview.reload} />
  const o = overview.data!

  return (
    <>
      <PageHeader
        title="Reports & exports"
        subtitle="Aggregated welfare reporting for leadership. Individual data is never included."
        action={<Button variant="ghost" onClick={doPrint}><Printer size={14} /> Print / save as PDF</Button>}
      />

      {/* printable overview */}
      <div ref={printRef} className="print:block">
        <Card title="Monthly welfare overview — live snapshot" subtitle={fmtDateTime(o.generated_at)}>
          <div className="grid gap-4 lg:grid-cols-5">
            <div className="lg:col-span-2">
              <RiskPie counts={o.current_risk_distribution} />
            </div>
            <ul className="space-y-2 self-center text-sm lg:col-span-3">
              <li className="flex justify-between rounded-xl bg-subtle px-3 py-2 ring-1 ring-line">
                <span className="text-slate-300">Total personnel</span><strong>{o.total_personnel}</strong>
              </li>
              <li className="flex justify-between rounded-xl bg-subtle px-3 py-2 ring-1 ring-line">
                <span className="text-slate-300">High / Moderate / Low</span>
                <strong>{o.current_risk_distribution.High} / {o.current_risk_distribution.Moderate} / {o.current_risk_distribution.Low}</strong>
              </li>
              <li className="flex justify-between rounded-xl bg-subtle px-3 py-2 ring-1 ring-line">
                <span className="text-slate-300">Open early-warning alerts</span><strong>{o.open_alerts}</strong>
              </li>
              <li className="flex justify-between rounded-xl bg-subtle px-3 py-2 ring-1 ring-line">
                <span className="text-slate-300">Interventions by status</span>
                <strong className="text-right">{Object.entries(o.interventions_by_status).map(([s, n]) => `${s.replace('_', ' ')}: ${n}`).join(', ')}</strong>
              </li>
            </ul>
          </div>
          <p className="mt-3 text-xs leading-relaxed text-slate-500">{o.note}</p>
          <p className="mt-1 hidden print:block text-[10px] text-slate-400">{FOOTER_NOTE}</p>
        </Card>
      </div>

      <Card className="mt-4" title="Report library"
            action={<Badge>demo · generated by {list.data?.items[0]?.generated_by ?? 'System'}</Badge>}>
        {list.status === 'loading' ? <Spinner /> : list.error ? <ErrorNote message={list.error} onRetry={list.reload} /> : (
          <DataTable<ReportT>
            rows={list.data!.items}
            keyOf={(r) => r.id}
            columns={[
              {
                header: 'Title',
                cell: (r) => (
                  <div className="flex items-center gap-2.5">
                    <FileDown size={14} className="text-sky-300" />
                    <span className="font-medium text-slate-200">{r.title}</span>
                  </div>
                ),
              },
              { header: 'Category', cell: (r) => <Badge>{r.category}</Badge> },
              { header: 'Period', cell: (r) => r.period },
              { header: 'Created', cell: (r) => fmtDate(r.created_at) },
            ]}
          />
        )}
      </Card>
    </>
  )
}
